### ISSUE TITLE
All settings are reset on server switch

### ISSUE THREAD

**Issue by LaserSlime** [LunarClient/Apollo#78] opened 2023-12-15 23:02 UTC
All custom mod and probably module settings too are reset after a player switches servers on waterfall (might affect velocity too)

Also, gonna mention this since it will be related to fixing this issue. Can you please make it so that
1. all disabled mods are announced in one message popup instead of a seperate one for each
2. each mod change is only announced once and not with every server switch like in the old api

**Comment by vopswtf** [comment] 2023-12-17 23:04
isn't this how it's suppose to work so different servers on one network can have different settings?

**Comment by LaserSlime** [comment] 2023-12-18 16:12
Then what would be the point of installing the plugin on a proxy? Also when you switch back servers the settings don't return.

**Comment by colinmcdonald22** [comment] 2023-12-18 16:37
> all disabled mods are announced in one message popup instead of a seperate one for each

This is now resolved in the latest client release

**Comment by theFoxley** [comment] 2023-12-18 23:00
still bugging, when switching server on a velocity proxy, the rule "1.8 delay" no longer works

**Comment by DiscowZombie** [comment] 2024-01-06 22:54
> still bugging, when switching server on a velocity proxy, the rule "1.8 delay" no longer works. It works only on the initial server

Hello,

This issue is still there. Any plan to solve it?

**Comment by TrentinTheKid** [comment] 2024-01-07 07:45
>     2. each mod change is only announced once and not with every server switch like in the old api

This issue was resolved in the [latest client release](https://www.lunarclient.com/changelog).

**Comment by TrentinTheKid** [comment] 2024-01-07 08:16
> All custom mod and probably module settings too are reset after a player switches servers on waterfall (might affect velocity too)

It doesn't appear to affect velocity (or at least I cannot reproduce it), can you send your configuration file(s) and what version of waterfall you're running? @LaserSlime

**Comment by DiscowZombie** [comment] 2024-01-07 11:16
> > All custom mod and probably module settings too are reset after a player switches servers on waterfall (might affect velocity too)
> 
> It doesn't appear to affect velocity (or at least I cannot reproduce it), can you send your configuration file(s) and what version of waterfall you're running? @LaserSlime

Plugin configuration: `plugins/apollo` folder (cf attached file). Using `Apollo v1.0.6` on Velocity.
(You can see the issue on `mc.uhcworld.fr` if it could help you)

[apollo.zip](https://github.com/LunarClient/Apollo/files/13853152/apollo.zip)

**Comment by TrentinTheKid** [comment] 2024-01-07 13:18
@DiscowZombie What issue are you specifically having? 

If you're referring to the "1.8 delay" being the only thing that breaks, the same as @theFoxley, we believe that's a different issue caused by a typo. It appears we accidentally named that specific config key after another one.

**Comment by LaserSlime** [comment] 2024-01-07 13:45
> > All custom mod and probably module settings too are reset after a player switches servers on waterfall (might affect velocity too)
> 
> It doesn't appear to affect velocity (or at least I cannot reproduce it), can you send your configuration file(s) and what version of waterfall you're running? @LaserSlime

I'm using waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560. 

Also idk if this is intended but the mod disable message now also doesnt show if you rejoin the entire server, not just when switching subservers.

**Comment by DiscowZombie** [comment] 2024-01-07 17:33
> @DiscowZombie What issue are you specifically having?

Disabled Mods aren't resent on server switch: the settings are only applied to the first server the user connect too.
See attached video for a demo. https://youtu.be/j75R24FtK6g

**Comment by colinmcdonald22** [comment] 2024-01-07 17:38
> > @DiscowZombie What issue are you specifically having?
> 
> Disabled Mods aren't resent on server switch: the settings are only applied to the first server the user connect too. See attached video for a demo. https://youtu.be/j75R24FtK6g

Got it. We will take a look, thank you

**Comment by TrentinTheKid** [comment] 2024-01-07 22:38
Can you both provide me with your discord usernames? I'd like to create a chat to have better communication. 

@DiscowZombie & @LaserSlime

**Comment by DiscowZombie** [comment] 2024-01-07 23:09
> Can you both provide me with your discord usernames? I'd like to create a chat to have better communication.
> 
> @DiscowZombie & @LaserSlime

Sure!

ID: `208986158665957376`
Username: `discowzombie`

**Comment by LaserSlime** [comment] 2024-01-08 15:36
> Can you both provide me with your discord usernames? I'd like to create a chat to have better communication.
> 
> @DiscowZombie & @LaserSlime

My discord is laserslime

**Comment by Gerrygames** [comment] 2024-03-27 21:23
Experiencing the same issue. Newest Lunar Client 1.20.4 on Velocity. Backend servers are 1.20.4 too. I would really like to disabled the cheats that are enabled by default (Minimap and Speed Hack when flying). Would really appreciate a fix :)

**Comment by TrentinTheKid** [comment] 2024-04-02 18:38
@LaserSlime - Can you enable friend request on Discord?

@Gerrygames - Can you provide me your Discord username and confirm you have friend request enabled?

**Comment by Gerrygames** [comment] 2024-04-02 18:43
@TrentinTheKid my Discord username is gerrygames and friend requests are enabled.

**Comment by LaserSlime** [comment] 2024-04-03 11:00
My discord is laserslime and I have now enabled friend requests from everyone.

**Comment by TrentinTheKid** [comment] 2024-04-07 20:59
This issue was resolved in the Lunar Client update: v2.14.8-2414

**Closed by TrentinTheKid** 2024-04-07 20:59 UTC
Labels: status: Accepted, type: Bug
